/**
 * Static storefront data (dummy JSON) — no network.
 * Shape matches API responses after catalog enrichment (arrays for images/tags).
 */
export const FIXTURE_PRODUCTS = [
  {
    id: 1,
    title: "Premium Sneakers",
    description: "High quality sneakers for everyday comfort.",
    price: 149.99,
    discountPercentage: 10,
    rating: 4.8,
    stock: 15,
    brand: "Stride",
    thumbnail: "https://picsum.photos/seed/ss1/400/400",
    images: [
      "https://picsum.photos/seed/ss1/800/800",
      "https://picsum.photos/seed/ss2/800/800",
    ],
    tags: ["shoes", "sneakers"],
    category: "footwear",
  },
  {
    id: 2,
    title: "Mock T-Shirt",
    description: "Soft cotton tee, relaxed fit.",
    price: 29.99,
    discountPercentage: 0,
    rating: 4.5,
    stock: 40,
    brand: "TestBrand",
    thumbnail: "https://picsum.photos/seed/ts1/400/400",
    images: ["https://picsum.photos/seed/ts1/800/800"],
    tags: ["apparel"],
    category: "clothing",
  },
  {
    id: 3,
    title: "Mock Jeans",
    description: "Classic straight-leg denim.",
    price: 59.99,
    discountPercentage: 15,
    rating: 4.0,
    stock: 22,
    brand: "TestBrand",
    thumbnail: "https://picsum.photos/seed/jn1/400/400",
    images: ["https://picsum.photos/seed/jn1/800/800"],
    tags: ["denim"],
    category: "clothing",
  },
  {
    id: 4,
    title: "Velvet Lounge Chair",
    description: "Statement chair for reading nooks.",
    price: 329.0,
    discountPercentage: 0,
    rating: 4.6,
    stock: 6,
    brand: "Hearth",
    thumbnail: "https://picsum.photos/seed/ch1/400/400",
    images: [
      "https://picsum.photos/seed/ch1/800/800",
      "https://picsum.photos/seed/ch2/800/800",
    ],
    tags: ["furniture", "living"],
    category: "furniture",
  },
  {
    id: 5,
    title: "Ceramic Table Lamp",
    description: "Warm ambient light with linen shade.",
    price: 89.5,
    discountPercentage: 5,
    rating: 4.3,
    stock: 18,
    brand: "Hearth",
    thumbnail: "https://picsum.photos/seed/lm1/400/400",
    images: ["https://picsum.photos/seed/lm1/800/800"],
    tags: ["lighting"],
    category: "furniture",
  },
  {
    id: 6,
    title: "Hydrating Face Serum",
    description: "Lightweight daily serum.",
    price: 42.0,
    discountPercentage: 0,
    rating: 4.7,
    stock: 50,
    brand: "GlowLab",
    thumbnail: "https://picsum.photos/seed/bty1/400/400",
    images: ["https://picsum.photos/seed/bty1/800/800"],
    tags: ["skincare"],
    category: "beauty",
  },
  {
    id: 7,
    title: "Matte Lip Set",
    description: "Three wearable shades in a giftable tin.",
    price: 36.0,
    discountPercentage: 20,
    rating: 4.2,
    stock: 30,
    brand: "GlowLab",
    thumbnail: "https://picsum.photos/seed/bty2/400/400",
    images: ["https://picsum.photos/seed/bty2/800/800"],
    tags: ["makeup"],
    category: "beauty",
  },
  {
    id: 8,
    title: "Wool Throw Blanket",
    description: "Cozy layer for sofas and beds.",
    price: 78.0,
    discountPercentage: 0,
    rating: 4.9,
    stock: 12,
    brand: "Hearth",
    thumbnail: "https://picsum.photos/seed/bl1/400/400",
    images: ["https://picsum.photos/seed/bl1/800/800"],
    tags: ["home", "textile"],
    category: "furniture",
  },
];
